### PR TITLE
Add support for net8.0-ios

### PR DESCRIPTION
**Pull request by danardelean**
This commit adds support for net8.0-ios to the library and the MauiApp test. 

It will only work on the device  (no support for iossimulator runtime) Supported runtime: ios-arm64

MauiApp - added the code to associate the first page image to the Image control

### CODE REVIEW

**Comment by sungaila** [comment]
Have you tried this on a real iOS and iPadOS device?

With missing support for Mac Catalyst and simulated iOS, it's odd that iOS/iPadOS works "just like that".

**Comment by danardelean** [comment]
IMG_DDB98FEA8533-1

**Comment by danardelean** [comment]
Of course the only thing that I'be tested and works is :
_bitmap = PDFtoImage.Conversion.ToImage(ms, 0); 
I have to try to run all the tests on iOS and see if they pass

**Comment by sungaila** [comment]
Great, I will merge your pull request (after a few changes) and build a test version. Thanks for your help! :-)

**Review by sungaila — APPROVED** [review]

**Comment by sungaila** [comment]
@danardelean I've released [PDFtoImage 5.0.0-preview](https://www.nuget.org/packages/PDFtoImage/5.0.0-preview) for testing. Please check if the iOS builds are still working if you have the time.

**Pull request merged**
