### PR TITLE
Implement path resolution that accounts for shadow copying

### LINKED ISSUE #2: Loading of pdfium.dll fails when running in an IIS context
Because IIS is shadow copying files you will get a path like `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\b7dc711f\a2c2b98f\assembly\dl3\8b76e845\0097b45e_1094d701\` when you call `Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)`, and not the original path of the dll.

I'm not sure how to fix this in a way that works across all runtimes and environments. It would be nice if you could provide a pdfium.dll path yourself.

### PR DESCRIPTION
**Pull request by JohannesEH**
Fixes #2. There might be a better way of getting the bin folder that works across all conceivable execution contexts.

### CODE REVIEW

**Review by sungaila — APPROVED** [review]

**Comment by sungaila** [comment]
Hi @JohannesEH,

thank you for fixing this issue. This might fix the problem [someone else has when hosting his ASP.NET MVC web app](https://github.com/sungaila/PDFtoZPL/issues/6).

**Comment by JohannesEH** [comment]
Yeah, that was the same problem I was seeing. After some investigating I found out that shadow copying was the culprit.

Thanks for accepting the fix! And thanks for making this project, is has helped me a lot the last week. 👍 

Now I'm just waiting for the package to get through nuget.org. :)

**Comment by sungaila** [comment]
@JohannesEH [Just uploaded the 1.1.2 package.](https://www.nuget.org/packages/PDFtoImage/1.1.2) Could you please double-check?

**Comment by JohannesEH** [comment]
Whoop it is there now. Thanks! :D

**Pull request merged**
